name: Deploy frontend

on:
  push:
    branches: [ Production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
    - run: npm install
      working-directory: Frontend
    - run: npm run build
      working-directory: Frontend
      env:
        CI: false
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: Frontend/build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build
          path: schmeck/build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./Frontend
